# Generated by Django 4.2.1 on 2023-05-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='authorized_user_read',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='unauthorized_user_read',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='authorized_user_CRUD',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='unauthorized_user_read',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='authorized_user_CRUD',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
