# Generated by Django 4.2.1 on 2023-05-22 21:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_folder_authorized_user_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='user_update',
            field=models.CharField(default=django.contrib.auth.models.User, verbose_name=django.contrib.auth.models.User),
        ),
    ]
