# Generated by Django 4.2.1 on 2023-05-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_remove_task_old_version_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
