# Generated by Django 4.2.1 on 2023-05-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_folder_user_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='user_update',
        ),
    ]
